services:
  upload:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Storage__ActiveStorageService=FileSystemStorageService
      - Storage__FileSystemStorageService__BasePath=/tmp/doris-data
      - Storage__FileSystemStorageService__TempFilePath=/tmp
      - Authorization__JwksUri=http://upload:8080/jwks
      - Authorization__CorsAllowedOrigins__0=http://upload:8080
      - PublicUrl=http://upload:8080