version: '3.4'

services:
  upload:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8051:8051
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8051
